server:
  port: 7000
spring:
  application:
    name: zhihu
  datasource:
    username: root
    password: zhangyukang
    url: jdbc:mysql://localhost:3306/zhihu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    password: zhangyukang
    host: 119.91.30.131
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  mail:
    host: smtp.qq.com
    username: 3053161401@qq.com
    password: xxxxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
        debug: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
